port: 3000
loglevel: info
persist: true
mongodburl: mongodb://root:secretpassword@mongol-mongodb-replicaset-0.mongol-mongodb-replicaset,mongol-mongodb-replicaset-1.mongol-mongodb-replicaset,mongol-mongodb-replicaset-2.mongol-mongodb-replicaset:27017/echo?authSource=admin
dbname: echo
delete: true
